<<<<<<< HEAD

#mybatis:
  # spring boot集成mybatis的方式打印sql
 # configuration:
  #  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
=======
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countsql
  
mybatis:
  type-aliases-package: com.woniu.team2project.entity

>>>>>>> branch 'master' of https://github.com/evenliew/team2project.git
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///team2project?serverTimezone=Asia/Shanghai
    username: root
    password: 941117
    type: com.alibaba.druid.pool.DruidDataSource
#   数据源
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true  
connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
